### ISSUE TITLE
Throttling broken when set to a value below 1 minute (60)

### ISSUE THREAD

**Issue by bengalih** [ulygit/asus_rt_ac68u#10]
If the throttle value is set below 60 seconds it appears that the last_run_time comparison to current_time will be inaccurate because the last_run_time is recorded in the log only in minutes and thus any call to compare them within the same minute will cause the update to succeed instead of be throttled.

This isn't normally an issue except in testing.  However if the value was set to below 60 and a script were to call it frequently, it would execute continuously making calls to cloudflare possibly several times per second.

**Comment by ulygit** [comment]
Looks good.
