### ISSUE TITLE
symbolic link

### ISSUE THREAD

**Issue by k1nghat** [ulygit/asus_rt_ac68u#2]
ive moved some of my stuffs to a vps, what is the best way to disable the script? just delete everything?
.cloudflare
cloudflare_ddns
cloudflare_ddns.log
ddns-start -> cloudflare_ddns

ive left it alone but notice that it kicks my vps ip off and sets the A name to my local ip so i need to do something with it. if i run something locally again i will point it to a subaddress i think.

i think the symbolic link will need to go because i tried to see if i could just switch the DDNS setting back to the free no-ip one i was using before but i think that triggered it to kick my A name back again.

**Comment by ulygit** [comment]
I've updated the main page with removal instructions (link below). Give it a try and let me know if you have any trouble. Incidentally, you should be able to simply turn off DDNS from the web portal without deleting anything. That leaves you the option of simply re-enabling it and having everything kick off again.

[Script Removal](https://github.com/ulygit/asus_rt_ac68u#script-removal)
