### ISSUE TITLE
Question - how exactly does the script get the router IP when it's executed automatically?

### ISSUE THREAD

**Issue by VladDBA** [ulygit/asus_rt_ac68u#24]
Hello,

The title pretty much covers the question I have, I see no way within the script to determine the router's WAN IP so I was wondering if there's a wrapper script I need to create, or if the router provides its WAN IP as input when it executes the script.

Thank you.

**Comment by bengalih** [comment]
Merlin firmware calls this as a custom DNS script.  It passes the WAN IP to the script.  So can consider the code in the firmware as the "wrapper" as it were.

**Comment by VladDBA** [comment]
Awesome! Thank you for the quick reply!
